version: '3.6'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
     - 3306:3306
    env_file: .env
    command:
      - --character-set-client-handshake=FALSE
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - /var/lib/mysql:/var/lib/mysql