server:
  port: 8080

spring:
  profiles:
    active: dev
    include: aws, ethereum, azure

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
    s3:
      bucket: blockai-bucket


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
